spring:
  application:
    name: water-consumption-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
water-consumption-service:
  irrigationArea: 500.0
  appliedBlade: 2.0